spring.application.name=demo
spring.application.name=demo
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.rzjznkjosjirovywlnhe
spring.datasource.password=LivUniSketchle!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
supabase.url=https://rzjznkjosjirovywlnhe.supabase.co
supabase.key=${SUPABASE_KEY:}
gcp.config.path=file:./serviceAccountKey.json
gcp.config.path=file:${GCP_KEY_PATH}